2024-05-24 20:20:05,699 INFO    MainThread:36492 [wandb_setup.py:_flush():76] Current SDK version is 0.17.0
2024-05-24 20:20:05,699 INFO    MainThread:36492 [wandb_setup.py:_flush():76] Configure stats pid to 36492
2024-05-24 20:20:05,699 INFO    MainThread:36492 [wandb_setup.py:_flush():76] Loading settings from C:\Users\Hasnan Ramadhan\.config\wandb\settings
2024-05-24 20:20:05,699 INFO    MainThread:36492 [wandb_setup.py:_flush():76] Loading settings from D:\classification_test\wandb\settings
2024-05-24 20:20:05,699 WARNING MainThread:36492 [wandb_setup.py:_flush():76] Unknown environment variable: WANDB_DEBUG
2024-05-24 20:20:05,699 INFO    MainThread:36492 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'_graphql_timeout_seconds': '300', 'init_timeout': '600'}
2024-05-24 20:20:05,699 INFO    MainThread:36492 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'train.py', 'program_abspath': 'D:\\classification_test\\train.py', 'program': 'D:\\classification_test\\train.py'}
2024-05-24 20:20:05,699 INFO    MainThread:36492 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-05-24 20:20:05,699 INFO    MainThread:36492 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-05-24 20:20:05,699 INFO    MainThread:36492 [wandb_init.py:_log_setup():520] Logging user logs to D:\classification_test\wandb\run-20240524_202005-bit0shfz\logs\debug.log
2024-05-24 20:20:05,699 INFO    MainThread:36492 [wandb_init.py:_log_setup():521] Logging internal logs to D:\classification_test\wandb\run-20240524_202005-bit0shfz\logs\debug-internal.log
2024-05-24 20:20:05,699 INFO    MainThread:36492 [wandb_init.py:init():560] calling init triggers
2024-05-24 20:20:05,699 INFO    MainThread:36492 [wandb_init.py:init():567] wandb.init called with sweep_config: {}
config: {'epochs': 15, 'batch_size': 32, 'lr': 0.0001}
2024-05-24 20:20:05,699 INFO    MainThread:36492 [wandb_init.py:init():605] wandb.init() called when a run is still active
2024-05-24 20:20:15,424 WARNING MsgRouterThr:36492 [router.py:message_loop():77] message_loop has been closed
